export { FIRST_EVENT_TYPE } from './extensibleEventSubject'
export { createStore } from './eventStore'
export { createEventBuilder } from './eventBuilder'
export { createAggregator } from './aggregator/index'
export { createAggregatorFactory, snapshot } from './aggregator/factory'
export { fromReducer } from './aggregator/fromReducer'
export { parseStoreArgs, withSimpleStoreSignature } from './parseStoreArgs'
